# ~/.config/tmuxinator/azure-devops-bot.yml
# Smart tmux dev environment for Azure DevOps Bot project

name: azure-devops-bot
root: ~/code/azure-devops-bot

# Project hooks - runs on project start
on_project_start: |
  source ~/.config/tmuxinator/scripts/common-setup.sh
  setup_logs "azure_devops_bot"
  setup_vscode_marker "azure_devops_bot"

# Run on project stop - cleanup
on_project_stop: |
  source ~/.config/tmuxinator/scripts/common-setup.sh
  cleanup_vscode_marker "azure_devops_bot"

# Runs before each window starts
pre_window: |
  source ~/.config/tmuxinator/scripts/common-setup.sh
  open_vscode_once "azure_devops_bot"

# Set window base-index to 1 and load tmux config
tmux_options: -f ~/.tmux.conf

# Start with the first window (claude)
startup_window: claude
startup_pane: 1
windows:
  - claude:
      root: ~/code/azure-devops-bot
      panes:
        - |
          source ~/.config/tmuxinator/scripts/common-setup.sh
          pane_setup "claude"
          claude
  - lazygit:
      root: ~/code/azure-devops-bot
      panes:
        - |
          source ~/.config/tmuxinator/scripts/common-setup.sh
          pane_setup "git"
          lazygit
  - dev:
      root: ~/code/azure-devops-bot
      panes:
        - |
          source ~/.config/tmuxinator/scripts/common-setup.sh
          pane_setup "dev" "dev"
          pnpm dev 2>&1 | tee -a .logs/dev/dev.$(date +%s).log
  - prisma:
      root: ~/code/azure-devops-bot
      panes:
        - |
          source ~/.config/tmuxinator/scripts/common-setup.sh
          pane_setup "prisma" "prisma"
          pnpm prisma studio 2>&1 | tee -a .logs/prisma/prisma.$(date +%s).log
