# ~/.config/tmuxinator/mnemosyne.yml
# Smart tmux dev environment for Next.js + Prisma + Storybook project

name: mnemosyne
root: ~/code/mnemosyne

# Project hooks - runs on project start
on_project_start: |
  source ~/.config/tmuxinator/scripts/common-setup.sh
  setup_logs "mnemosyne"
  setup_vscode_marker "mnemosyne"

# Run on project stop - cleanup
on_project_stop: |
  source ~/.config/tmuxinator/scripts/common-setup.sh
  cleanup_vscode_marker "mnemosyne"

# Runs before each window starts
pre_window: |
  source ~/.config/tmuxinator/scripts/common-setup.sh
  open_vscode_once "mnemosyne"

# Set window base-index to 1 and load tmux config
tmux_options: -f ~/.tmux.conf

# Start with the first window (claude)
startup_window: claude
startup_pane: 1
windows:
  - claude:
      root: ~/code/mnemosyne
      panes:
        - |
          source ~/.config/tmuxinator/scripts/common-setup.sh
          pane_setup "claude"
          claude
  - git:
      root: ~/code/mnemosyne
      panes:
        - |
          source ~/.config/tmuxinator/scripts/common-setup.sh
          pane_setup "git"
          git
  - nextjs:
      root: ~/code/mnemosyne
      panes:
        - |
          source ~/.config/tmuxinator/scripts/common-setup.sh
          pane_setup "nextjs" "nextjs"
          pnpm dev 2>&1 | tee -a .logs/nextjs/nextjs.$(date +%s).log | pnpm exec pino-pretty
  - storybook:
      root: ~/code/mnemosyne
      panes:
        - |
          source ~/.config/tmuxinator/scripts/common-setup.sh
          pane_setup "storybook" "storybook"
          pnpm storybook 2>&1 | tee -a .logs/storybook/storybook.$(date +%s).log
  - prisma:
      root: ~/code/mnemosyne
      panes:
        - |
          source ~/.config/tmuxinator/scripts/common-setup.sh
          pane_setup "prisma" "prisma"
          pnpm prisma studio 2>&1 | tee -a .logs/prisma/prisma.$(date +%s).log
