github.com:
    - user: nathanvale
      git_protocol: ssh
      ssh_key: ~/.ssh/id_rsa
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor: code
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to, e.g. "less". Set the value to "cat" to disable the pager.
pager: bat
# Aliases allow you to create nicknames for gh commands
aliases:
    co: pr checkout
    ci: issue create
    cp: pr create
browser: open
version: "1"
